### ISSUE TITLE
BMP280: bmp280_init() not executing because of wrong descriptor initialization

### ISSUE THREAD

**Issue by Tristaan** [UncleRus/esp-idf-lib#233] opened 2021-07-18 18:03 UTC
**Device type**:

- [x] ESP32

**Framework version**:

- [x] ESP-IDF latest master

**Describe the bug**:

This bug happened to me after getting around #7 using the FAQ, to set the `CONFIG_I2CDEV_NOLOCK`, to prevent the usage of semaphores.
There are actually two things happening the clk_flags being unset, so they are not initialized to 0 as they should be. Then the next part is the unitialized timeout_ticks, which should also be set to 0.

#232 addresses this issue.

**Comment by UncleRus** [comment] 2021-07-19 02:14
It's not a bug. It is up to the application, not the driver, to clear the descriptor before use. Take a close look at the examples:
```C
...
    bmp280_t dev;
    memset(&dev, 0, sizeof(bmp280_t));
...
// or
    i2c_dev_t dev;
    memset(&dev, 0, sizeof(i2c_dev_t));

```
I am closing this issue and its associated pull request.

**Closed by UncleRus** 2021-07-19 02:14 UTC
